"""Stable tool error codes for agents and /v1 responses."""

GMAIL_SESSION_EXPIRED = "GMAIL_SESSION_EXPIRED"
GMAIL_FETCH_FAILED = "GMAIL_FETCH_FAILED"
AI_UNAVAILABLE = "AI_UNAVAILABLE"
NOT_FOUND = "NOT_FOUND"
APPROVAL_INVALID = "APPROVAL_INVALID"
SEND_FAILED = "SEND_FAILED"
SCHEDULE_FAILED = "SCHEDULE_FAILED"
